name: Question
description: Ask a question that needs answering.
title: "[Q/A]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Ask away. Please be direct, but polite :)

  - type: textarea
    id: question
    attributes:
      label: "My question:"
      placeholder: |
        Why are bananas so yummy?
    validations:
      required: true
